"""Synthesize an isolated dev-runtime config from the production config (#271).

The dev config is the production config with exactly three overrides -- the isolation
levers -- applied: ``[server].state_root`` (isolated operation/worker state),
``[tunnel].id`` and ``[tunnel].profile`` (distinct tunnel identity). It is emitted as
one ``key = <inline-table>`` line per top-level key, which is valid TOML and round-trips
through the parser, so the full production structure (repos, profiles, steps) is
preserved verbatim while only the three isolation keys change.
"""

from __future__ import annotations

import json
import os
from pathlib import Path

import tomli as tomllib

from ...domain.errors import ConfigError


class TomlDevConfigProvisioner:
    def provision(
        self,
        base_config: Path,
        dev_config: Path,
        *,
        state_root: Path,
        tunnel_id: str,
        profile: str,
    ) -> None:
        try:
            raw = tomllib.loads(base_config.read_text(encoding="utf-8"))
        except (OSError, tomllib.TOMLDecodeError) as exc:
            raise ConfigError(f"DEV_CONFIG_BASE_UNREADABLE: {base_config}: {exc}") from exc

        document = dict(raw)
        server = dict(document.get("server") or {})
        server["state_root"] = str(state_root)
        document["server"] = server
        tunnel = dict(document.get("tunnel") or {})
        tunnel["id"] = tunnel_id
        tunnel["profile"] = profile
        document["tunnel"] = tunnel

        text = render_flat_toml(document)
        dev_config.parent.mkdir(parents=True, exist_ok=True)
        tmp = dev_config.with_name(f".{dev_config.name}.tmp-{os.getpid()}")
        try:
            with tmp.open("w", encoding="utf-8") as handle:
                handle.write(text)
                handle.flush()
                os.fsync(handle.fileno())
            os.replace(tmp, dev_config)
        finally:
            tmp.unlink(missing_ok=True)


def render_flat_toml(document: dict[str, object]) -> str:
    """Render a TOML document as one ``key = <inline value>`` line per top-level key."""
    header = "# Generated by RepoForge dev-runtime. Isolated candidate config.\n"
    lines = [f"{_bare_key(key)} = {_toml_value(document[key])}" for key in sorted(document)]
    return header + "\n".join(lines) + "\n"


def _bare_key(key: str) -> str:
    # TOML bare keys allow [A-Za-z0-9_-]; anything else must be quoted.
    if key and all(character.isalnum() or character in "_-" for character in key):
        return key
    return json.dumps(key, ensure_ascii=False)


def _toml_value(value: object) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, int):
        return str(value)
    if isinstance(value, float):
        return repr(value)
    if isinstance(value, str):
        return json.dumps(value, ensure_ascii=False)
    if isinstance(value, list):
        return "[" + ", ".join(_toml_value(item) for item in value) + "]"
    if isinstance(value, dict):
        entries = ", ".join(f"{_bare_key(str(key))} = {_toml_value(value[key])}" for key in value)
        return "{" + entries + "}"
    raise ConfigError(f"DEV_CONFIG_UNSUPPORTED_VALUE: {type(value).__name__}")
