"""Immutable configuration generation persistence boundary."""

from __future__ import annotations

from pathlib import Path
from typing import Protocol

from ..domain.config_generation import ConfigGeneration, ConfigMutation


class ConfigurationStore(Protocol):
    @property
    def source_path(self) -> Path: ...
    @property
    def root(self) -> Path: ...
    @property
    def active_resolved_path(self) -> Path: ...
    def current(self) -> ConfigGeneration | None: ...
    def active(self) -> ConfigGeneration | None: ...
    def activation_target(self) -> ConfigGeneration | None: ...
    def stage_activation(
        self, generation: int, *, expected_active: int | None = None
    ) -> ConfigGeneration: ...
    def clear_activation_target(self, *, expected_generation: int | None = None) -> None: ...
    def history(self) -> tuple[ConfigGeneration, ...]: ...
    def next_generation(self) -> int: ...
    def read_source_text(self) -> str: ...
    def generation_path(self, generation: int) -> Path: ...
    def resolved_path(self, generation: int) -> Path: ...
    def read_resolved_text(self, generation: int | None = None) -> str: ...
    def accept(self, mutation: ConfigMutation) -> ConfigGeneration: ...
    def activate(
        self, generation: int, *, expected_active: int | None = None
    ) -> ConfigGeneration: ...
    def import_legacy(
        self, source_text: str, resolved_text: str, *, created_at: str
    ) -> ConfigGeneration: ...
    def rollback(
        self,
        generation: int,
        *,
        expected_active: int | None,
        approval_token: str | None = None,
    ) -> ConfigGeneration: ...
