"""Local filesystem boundary used by application use cases."""

from __future__ import annotations

from pathlib import Path
from typing import Protocol


class FileSystem(Protocol):
    def exists(self, path: Path) -> bool: ...

    def is_dir(self, path: Path) -> bool: ...

    def is_file(self, path: Path) -> bool: ...

    def is_symlink(self, path: Path) -> bool: ...

    def size(self, path: Path) -> int: ...

    def read_bytes(self, path: Path) -> bytes: ...

    def read_text(self, path: Path) -> str: ...

    def write_bytes_atomic(
        self, path: Path, data: bytes, *, preserve_mode: bool = True
    ) -> None: ...

    def unlink(self, path: Path, *, missing_ok: bool = False) -> None: ...

    def mkdir(self, path: Path, *, parents: bool = True, exist_ok: bool = True) -> None: ...
