"""Semantic Git repository/worktree boundary."""

from __future__ import annotations

from pathlib import Path
from typing import Any, Protocol

from ..config import ProfileConfig, RepositoryConfig
from .command import CommandExecutor, CommandResult


class GitRepository(Protocol):
    @property
    def executor(self) -> CommandExecutor: ...

    def is_worktree(self, path: Path) -> bool: ...

    def diff_stat(self, path: Path) -> str: ...

    def current_branch(self, path: Path) -> str: ...

    def head_sha(self, path: Path) -> str: ...

    def status_porcelain(self, path: Path) -> str: ...

    def status_short_branch(self, path: Path) -> str: ...

    def remote_verbose(self, path: Path) -> str: ...

    def changed_paths(self, path: Path, repo: RepositoryConfig) -> list[str]: ...

    def untracked_paths(self, path: Path, repo: RepositoryConfig) -> list[str]: ...

    def fingerprint(self, path: Path) -> str: ...

    def change_metrics(self, path: Path, repo: RepositoryConfig) -> dict[str, Any]: ...

    def enforce_change_budget(self, path: Path, repo: RepositoryConfig) -> dict[str, Any]: ...

    def ensure_clean(self, path: Path, *, context: str) -> None: ...

    def ahead_of_base(self, path: Path, remote: str, base: str) -> int: ...

    def list_files(
        self, path: Path, repo: RepositoryConfig, max_entries: int
    ) -> tuple[list[str], bool]: ...

    def root_files(self, path: Path, repo: RepositoryConfig) -> list[str]: ...

    def recent_commits(self, path: Path, limit: int) -> list[dict[str, str]]: ...

    def search(
        self,
        path: Path,
        repo: RepositoryConfig,
        query: str,
        path_glob: str | None,
        max_results: int,
    ) -> tuple[list[str], bool]: ...

    def diff(self, path: Path, repo: RepositoryConfig, *, staged: bool) -> dict[str, Any]: ...

    def run_profile(
        self, path: Path, profile: ProfileConfig
    ) -> tuple[list[CommandResult], str, dict[str, Any]]: ...

    def restore_paths(
        self, path: Path, repo: RepositoryConfig, relative_paths: list[str]
    ) -> tuple[list[str], list[str]]: ...

    def create_worktree(
        self, repo: RepositoryConfig, destination: Path, branch: str, base: str
    ) -> str: ...

    def remove_worktree(
        self, repo: RepositoryConfig, path: Path, branch: str, delete_branch: bool
    ) -> bool: ...

    def commit(self, path: Path, message: str) -> tuple[str, str]: ...

    def push(self, path: Path, remote: str, branch: str, timeout: int) -> CommandResult: ...

    def upstream_name(self, path: Path) -> str | None: ...

    def upstream_sha(self, path: Path) -> str: ...

    def apply_patch(self, path: Path, patch: str) -> None: ...

    def reverse_patch(self, path: Path, patch: str) -> None: ...

    def remote_url(self, path: Path, remote: str) -> CommandResult: ...

    def verify_base(self, path: Path, remote: str, base: str) -> CommandResult: ...
