"""Presentation-neutral guided onboarding interaction boundary."""

from typing import Protocol


class OperatorIO(Protocol):
    @property
    def interactive(self) -> bool: ...
    def show(self, event: dict[str, object]) -> None: ...
    def choose(self, *, prompt: str, choices: tuple[str, ...]) -> str: ...
    def ask(self, *, prompt: str, secret: bool = False) -> str: ...
    def confirm(self, *, prompt: str, default: bool = False) -> bool: ...
